/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package txman

import kotlin.test.Test

class TxManTest {
    @Test fun someLibraryMethodReturnsTrue() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
